module.exports = {
    C: 'c',
    CPP: 'cpp',
    PYTHON: 'python',
    JAVA: 'java',
    NODEJS: 'nodejs',
    RUBY: 'ruby',
    DART: 'dart',
    REACT_NATIVE: 'react-native',
    CSHARP: 'csharp',
    PROMPTV1: 'promptv1',
    PROMPTV2: 'promptv2',
    MULTIFILE: 'multifile',
    SQLITE3: 'sqlite3',
}
